---
title: "question_19"
author: "Yuese Li"
date: "May 13, 2024"
format: 
  html: 
    embed-resources: true
    code-tools: true
editor: source
---

```{r}
# Load packages
library(bayesrules)
library(tidyverse)
library(dplyr)
library(janitor)
library(ggplot2)
library(mosaic)
```

```{r}
plot_beta(4, 3)
```


```{r}
summarize_beta_binomial(alpha = 0.5, beta = 1, y = 3, n = 7)
plot_beta_binomial(alpha = 4, beta = 3, y = 20, n = 100)
```

```{r}
# Load packages
library(bayesrules)
library(tidyverse)
library(dplyr)
library(janitor)
library(ggplot2)
library(mosaic)
```

```{r}
# Import data
data(bechdel, package = "bayesrules")

# Set seed
set.seed(33993)
```

```{r}
# a
data_1980 <- bechdel |>
  filter(year == 1980) |>
  tabyl(binary)

data_1980$n[1] 
data_1980$n[2] 
```

```{r}
# b
data_1990 <- bechdel |>
  filter(year == 1990) |>
  tabyl(binary)

data_1990$n[1] 
data_1990$n[2] 
```

```{r}
# c
data_2000 <- bechdel |>
  filter(year == 2000) |>
  tabyl(binary)

data_2000$n[1] 
data_2000$n[2] 
```



