```{r}
# Load necessary libraries
library(rstan)
library(bayesplot)
library(magrittr)
library(tidyverse)
library(janitor)
```

```{r}
# a
# STEP 1: DEFINE the model
normal_normal_model <- "
  data {
    int<lower=0> N; // number of observations
    real Y[N]; // observed data
  }
  parameters {
    real mu; // mean parameter
  }
  model {
    Y ~ normal(mu, 1.3); // likelihood
    mu ~ normal(10, 1.2); // prior
  }
"

# STEP 2: SIMULATE the posterior
nn_sim <- stan(model_code = normal_normal_model, 
               data = list(N = 4, Y = c(7.1, 8.9, 8.4, 8.6)),  # observed data
               chains = 4,  # number of parallel Markov chains
               iter = 10000, # number of iterations per chain
               seed = 84735) # set a seed
```


```{r}
# b
# Trace plots of the 4 Markov chains
mcmc_trace(nn_sim, pars = "mu", size = 0.1)

# Density plots of the 4 Markov chains
mcmc_dens(nn_sim, pars = "mu") + 
  yaxis_text(TRUE) + 
  ylab("density")
```

```{r}
# d
plot_normal_normal(mean = 10,   
  sd = 1.2,      
  sigma = 1.3,    
  y_bar = mean(c(7.1, 8.9, 8.4, 8.6)), 
  n = 4,        
)
```

