```{r}
# Load packages
library(tidyverse)
library(janitor)
library(rstan)
library(bayesplot)
library(bayesrules)
```

```{r}
# a
# STEP 1: DEFINE the model
gp_model <- "
  data {
    int<lower = 0> Y[3]; // observed counts, it could be any non-negative integers
  }
  parameters {
    real<lower = 0> lambda; // rate parameter of the Poisson distribution, it could be any non-negative real number
  }
  model {
    Y ~ poisson(lambda); // likelihood: observed counts follow a Poisson distribution with rate parameter lambda
    lambda ~ gamma(20, 5); // prior: lambda follows a gamma distribution with shape 20 and rate 5
  }
"

# STEP 2: SIMULATE the posterior
gp_sim <- stan(model_code = gp_model, 
               data = list(Y = c(0, 1, 0)),  # observed counts are 0, 1, and 0
               chains = 4,  # number of parallel Markov chains
               iter = 10000, # number of iterations per chain
               seed = 84735) # set a seed

```


```{r}
# b 
# Trace plots of the 4 Markov chains
mcmc_trace(gp_sim, pars = "lambda", size = 0.1)

# Density plots of the 4 Markov chains
mcmc_dens(gp_sim, pars = "lambda") + 
  yaxis_text(TRUE) + 
  ylab("density")
```

```{r}
# d
plot_gamma_poisson(shape = 20, rate = 5, sum_y = 1, n = 3)
```

