```{r}
library(tidyverse)
library(janitor)
library(rstan)
library(bayesplot)
library(bayesrules)
```

```{r}
one_mh_iteration_normal <- function(s, current) {
  # STEP 1: Propose the next chain location
  proposal <- rnorm(1, mean = current, sd = s)
  
  # STEP 2: Decide whether or not to go there
  proposal_plaus <- dnorm(proposal, 0, 1) * dnorm(6.25, proposal, 0.75)
  current_plaus <- dnorm(current, 0, 1) * dnorm(6.25, current, 0.75)
  alpha <- min(1, proposal_plaus / current_plaus)
  next_stop <- sample(c(proposal, current), 
                      size = 1, prob = c(alpha, 1 - alpha))
  
  # Return the results
  return(data.frame(proposal, alpha, next_stop))
}
```

```{r}
mh_tour_normal <- function(N, s) {
  # 1. Start the chain at location 3
  current <- 3

  # 2. Initialize the simulation
  mu <- rep(0, N)

  # 3. Simulate N Markov chain stops
  for(i in 1:N) {    
    # Simulate one iteration
    sim <- one_mh_iteration_normal(s = s, current = current)
    
    # Record next location
    mu[i] <- sim$next_stop
    
    # Reset the current location
    current <- sim$next_stop
  }
  
  # 4. Return the chain locations
  return(data.frame(iteration = c(1:N), mu))
}

set.seed(84735)
```

```{r}
# a
mh_simulation_a <- mh_tour_normal(N = 20, s = 0.01)
```

```{r}
ggplot(mh_simulation_a, aes(x = iteration, y = mu)) + 
  geom_line()

ggplot(mh_simulation_a, aes(x = mu)) + 
  geom_histogram(aes(y = ..density..), color = "white", bins = 20) 
```

```{r}
# b
mh_simulation_a <- mh_tour_normal(N = 20, s = 10)
```

```{r}
ggplot(mh_simulation_a, aes(x = iteration, y = mu)) + 
  geom_line()

ggplot(mh_simulation_a, aes(x = mu)) + 
  geom_histogram(aes(y = ..density..), color = "white", bins = 20) 
```

```{r}
# c
mh_simulation_a <- mh_tour_normal(N = 1000, s = 0.01)
```

```{r}
ggplot(mh_simulation_a, aes(x = iteration, y = mu)) + 
  geom_line()

ggplot(mh_simulation_a, aes(x = mu)) + 
  geom_histogram(aes(y = ..density..), color = "white", bins = 20) 
```

```{r}
# d
mh_simulation_a <- mh_tour_normal(N = 1000, s = 10)
```

```{r}
ggplot(mh_simulation_a, aes(x = iteration, y = mu)) + 
  geom_line()

ggplot(mh_simulation_a, aes(x = mu)) + 
  geom_histogram(aes(y = ..density..), color = "white", bins = 20) 
```

```{r}
# f
mh_simulation_a <- mh_tour_normal(N = 1000, s = 1)
```

```{r}
ggplot(mh_simulation_a, aes(x = iteration, y = mu)) + 
  geom_line()

ggplot(mh_simulation_a, aes(x = mu)) + 
  geom_histogram(aes(y = ..density..), color = "white", bins = 20) 
```